In [29]:
import matplotlib.pyplot as plt
import pandas as pd
import pylab as pl
import numpy as np
from sklearn import preprocessing
%matplotlib inline

In [3]:
df=pd.read_csv('teleCust1000t.csv')
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [36]:
X=df[['region','tenure','age','address','income','ed','employ','custcat']].values
X[0:5]

array([[  2.,  13.,  44.,   9.,  64.,   4.,   5.,   1.],
       [  3.,  11.,  33.,   7., 136.,   5.,   5.,   4.],
       [  3.,  68.,  52.,  24., 116.,   1.,  29.,   3.],
       [  2.,  33.,  33.,  12.,  33.,   2.,   0.,   1.],
       [  2.,  23.,  30.,   9.,  30.,   1.,   2.,   3.]])

In [8]:
#we are gonna scale down this data between 0 n 1
y = df['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (800, 8) (800,)
Test set: (200, 8) (200,)


In [51]:
X_scaled = preprocessing.StandardScaler().fit(X).transform(X)
X_scaled[0:5]
np.mean(X_scaled)

3.97459842815806e-17

In [60]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [77]:
ks=10
mean_acc=np.zeros((ks-1))

for i in range(1,ks):
    neigh=KNeighborsClassifier(n_neighbors=i).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    mean_acc[i-1]=accuracy_score(y_test,yhat)
    
mean_acc

array([0.305, 0.33 , 0.285, 0.285, 0.33 , 0.32 , 0.37 , 0.345, 0.325])