In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.optimize as opt

In [4]:
df=pd.read_csv('ChurnData.csv')
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [8]:
churn_df=df[['tenure','age','income','employ','internet','ed','employ','equip','churn']]
churn_df[['churn']]=churn_df[['churn']].astype(int)
churn_df[['churn']]

c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pandas\core\frame.py:2963: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


churn
0        1
1        1
2        0
3        0
4        0
..     ...
195      0
196      0
197      0
198      1
199      0

[200 rows x 1 columns]

In [9]:
X=df[['tenure','age','income','employ','internet','ed','employ','equip']].values
X[0:5]

array([[ 11.,  33., 136.,   5.,   0.,   5.,   5.,   0.],
       [ 33.,  33.,  33.,   0.,   0.,   2.,   0.,   0.],
       [ 23.,  30.,  30.,   2.,   0.,   1.,   2.,   0.],
       [ 38.,  35.,  76.,  10.,   1.,   2.,  10.,   1.],
       [  7.,  35.,  80.,  15.,   0.,   2.,  15.,   0.]])

In [10]:
from sklearn import preprocessing 
X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491,  0.4751423 , -0.58477841, -0.88640526,
         1.6961288 , -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491, -0.32886061, -1.14437497, -0.88640526,
        -0.6433592 , -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.35227817, -0.92053635, -0.88640526,
        -1.42318853, -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854,  0.00679109, -0.02518185,  1.12815215,
        -0.6433592 , -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.03801451,  0.53441472, -0.88640526,
        -0.6433592 ,  0.53441472, -0.85972695]])

In [11]:
y=churn_df['churn']
y[0:5]

0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int32

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (150, 8) (150,)
Test set: (50, 8) (50,)


In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

TypeError: fit() missing 1 required positional argument: 'y'

In [25]:
yhat=LR.predict(X_test)
yhat[0:5]

array([0, 1, 0, 1, 0])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, yhat)

0.76